### ISSUE TITLE
Otros datasets

### ISSUE THREAD

**Issue by aaferrari** [gabriel-de-luca/covid-19#3]
Hola, encontré estos datasets que se podrían incorporar a OpenStreetMap (ya sea para agregar lugares nuevos o complementar la información de los ya existentes):

* [Listado de Establecimientos de Droguerías (Registro Federal de Droguerías)](https://datos.gob.ar/dataset/salud-listado-establecimientos-droguerias-redro)
* [Listado Establecimientos de Salud Asentados en el Registro Federal de Salud y Regulación Sanitaria](https://datos.gob.ar/dataset/salud-listado-establecimientos-salud-asentados-registro-federal-refes)
* [Listado de Establecimientos de Farmacias](https://datos.gob.ar/dataset/salud-listado-establecimientos-farmacias)
* [Registro Nacional de Prestadores de Establecimientos de Salud Inscriptos](https://datos.gob.ar/dataset/salud-registro-nacional-prestadores-establecimientos-salud-inscriptos)
* [Farmacias que dispensan medicamentos de PAMI](https://datos.gob.ar/dataset/pami-farmacias)
* [Datos georeferenciados de los Centros de Atención de PAMI](https://datos.gob.ar/dataset/pami-listado-unidades-gestion-local-ugl-agencias)
* [Mapa de los Centros de Salud](https://gobiernoabierto.cordoba.gob.ar/data/datos-abiertos/categoria/salud/mapa-de-los-centros-de-salud/3) (Gobierno Abierto Córdoba)

No se cuales ya se están usando pero salvo por el ultimo, los demás los encontré en https://datos.gob.ar/dataset?groups=heal
Actualmente no puedo dedicarle tiempo a este proyecto pero ahí lo dejo para quien este interesado.

**Comment by caprieldeluca** [comment]
> * [Listado de Establecimientos de Droguerías (Registro Federal de Droguerías)](https://datos.gob.ar/dataset/salud-listado-establecimientos-droguerias-redro)

El listado no está georreferenciado. Los códigos de establecimiento coinciden con los códigos de establecimiento de SISA. De las 1251 droguerías de este dataset, 852 ya están incluidas en el archivo [droguerias-sisa.geojson](https://github.com/gabriel-de-luca/covid-19/blob/master/droguerias-sisa.geojson), que son los registros que estaban georreferenciados del listado de droguerías del REFES consultado en el SISA.

---

> * [Listado Establecimientos de Salud Asentados en el Registro Federal de Salud y Regulación Sanitaria](https://datos.gob.ar/dataset/salud-listado-establecimientos-salud-asentados-registro-federal-refes)

El listado tampoco está georreferenciado. Los códigos de establecimiento coinciden con los códigos de establecimiento de SISA. De los 26985 establecimientos de este dataset, 25435 ya están incluidos en el archivo [establecimientos-sisa.geojson](https://github.com/gabriel-de-luca/covid-19/blob/master/establecimientos-sisa.geojson), que son los registros que estaban georreferenciados del listado de establecimientos del REFES consultado en el SISA.

---

> * [Listado de Establecimientos de Farmacias](https://datos.gob.ar/dataset/salud-listado-establecimientos-farmacias)

El listado tampoco está georreferenciado. Los códigos de establecimiento coinciden con los códigos de establecimiento de SISA. De las 13580 farmacias de este dataset, 6824 ya están incluidas en el archivo [farmacias-sisa.geojson](https://github.com/gabriel-de-luca/covid-19/blob/master/farmacias-sisa.geojson), que son los registros que estaban georreferenciados del listado de farmacias del REFES consultado en el SISA.

---

> * [Registro Nacional de Prestadores de Establecimientos de Salud Inscriptos](https://datos.gob.ar/dataset/salud-registro-nacional-prestadores-establecimientos-salud-inscriptos)

El listado no está georreferenciado, no tiene códigos de establecimiento ni direcciones postales. No tenemos manera de generar datos geoespaciales ni de cargar entidades en OSM en base a este dataset.

---

> * [Farmacias que dispensan medicamentos de PAMI](https://datos.gob.ar/dataset/pami-farmacias)

Los datos tienen una coordenada geográfica sola. El listado fue consultado anteriormente, se realizó una geocodificación en base a las direcciones postales y se cargaron los datos que devolvieron resultados geolocalizados en el archivo [farmacias-pami.geojson](https://github.com/gabriel-de-luca/covid-19/blob/master/farmacias-pami.geojson). 

---

> * [Datos georeferenciados de los Centros de Atención de PAMI](https://datos.gob.ar/dataset/pami-listado-unidades-gestion-local-ugl-agencias)

Es un listado de agencias principalmente. Tiene algunos centros de atención también. De los 686 registros de este dataset, 441 están georreferenciados. Se creó el archivo [agencias-pami.geojson](https://github.com/gabriel-de-luca/covid-19/blob/master/agencias-pami.geojson). 

---

> * [Mapa de los Centros de Salud](https://gobiernoabierto.cordoba.gob.ar/data/datos-abiertos/categoria/salud/mapa-de-los-centros-de-salud/3) (Gobierno Abierto Córdoba)

Es un conjunto de datos georreferenciados, en formato KML, de 106 establecimientos de salud (hospitales y centro de atención) en el departamento Capital de la provincia de Córdoba. Se creó el archivo [establecimientos-cordoba.geojson](https://github.com/gabriel-de-luca/covid-19/blob/master/establecimientos-cordoba.geojson).

---

> Actualmente no puedo dedicarle tiempo a este proyecto pero ahí lo dejo para quien este interesado.

¡Gracias!
